/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    id("io.freefair.lombok") version "6.3.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/OWNER/REPOSITORY")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.thesimplecloud.eu/artifactory/list/gradle-release-local/")
    }
}

dependencies {
    implementation("org.junit.jupiter:junit-jupiter-engine:5.0.2")
    implementation("mysql:mysql-connector-java:8.0.26")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    compileOnly("eu.thesimplecloud.simplecloud:simplecloud-api:2.3.0")
    compileOnly("eu.thesimplecloud.simplecloud:simplecloud-plugin:2.3.0")
    implementation(fileTree("C:/Users/caosk/Desktop/ServerAPI"))
    compileOnly("io.papermc.paper:paper-api:1.18.1-R0.1-SNAPSHOT")
    compileOnly("com.mojang:authlib:1.5.21")
}

group = "de.chaos.mc.server"
version = "1"
description = "MLGRush"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
